### ISSUE TITLE
Добавить метод проверки существования у объекта метода с указанным именем

### ISSUE THREAD

**Issue by leemuar** [oscript-library/asserts#2]
Для удобства хочу писать вместо

```
Рефлектор = Новый Рефлектор;
Ожидаем
   .Что(Рефлектор.МетодСуществует(Объект, "ИмяМетода"))
   .ЭтоИстина();
```

примерно следующее

```
Ожидаем
   .Что(Объект)
   .ИмеетМетод("ИмяМетода")
```

```
Ожидаем
   .Что(Объект)
   .Метод("ИмяМетода")
   .Существует()
```

```
Тестирование.МетодСуществует(Объект, "ИмяМетода");
```

**Comment by leemuar** [comment]
@artbear Есть возражения/замечания/предложения или можно присылать PR?

Предлагаю пока метод Существует() не менять, добавить только ИмеетМетод() и МетодСуществует()

**Comment by artbear** [comment]
PR всегда можно и нужно присылать!

>Предлагаю пока метод Существует() не менять, добавить только ИмеетМетод() и МетодСуществует()

Согласен

**Comment by artbear** [comment]
Выполнено
