### ISSUE TITLE
Библиотека asserts не тестируется через 1testrunner

### ISSUE THREAD

**Issue by artbear** [oscript-library/asserts#3]

**Comment by artbear** [comment]
Для полного исправления этой проблемы, как и проблемы тестирования любой дев-библиотеки при наличии prod-версии этой же библиотеки, нужно юзать следующую схему:
+ заменить в каталоге %OneScript%/lib файл `package-loader.os`  на [файл из моего gist-а](https://gist.github.com/artbear/d5aefeb0517965cfcadec80d59bf4232)
  * это главное неудобство, т.к. часто этот каталог залочен 
  + при установке новой версии движка движок заменяет этот файл на свой :(
+ запустить тестирование через `oscript tasks\tests.os`
  + `tasks\tests.os` я сделал достаточно универсальным, и для 1testrunner, и для 1bdd
  + возможно, в каких-то пакетах потребуется слегка поправить первую строку `Использовать ..` на `Использовать ../src`

При выполнении указанных действий проходит сборка именно дев-версии!

В этом легко убедиться - например, для asserts добавить `ВызватьИсключение 1;` в метод `Что`

Такой метод подходит, пока не будет финального решения с `oscript_modules` и opm, которое обещают сделать @nixel2007 и @EvilBeaver 

/cc @nixel2007 @EvilBeaver @pumbaEO @dmpas

**Comment by artbear** [comment]
Продублировал на форуме https://xdd.silverbulleters.org/t/problema-pri-testirovanii-asserts-biblioteka-testiruet-ne-sebya-a-versiyu-iz-standartnoj-biblioteki/1784/10

**Comment by leemuar** [comment]
Чем плох подход с ЗагрузитьСценарий()? Как. например, сделано здесь: https://github.com/oscript-library/asserts/blob/2fb2e614c186b4ef43eea3abc32a9ea859f253f2/tests/bdd-assertions-tests-additional.os

Да, тесты немного громоздкие получаются, но зато они независимые ни от чего, и тетсируют модуль изолированно.

**Comment by EvilBeaver** [comment]
Да в целом-то не плох, но и идеальным я бы не назвал. Скорее обходной маневр.

**Comment by nixel2007** [comment]
Настроил ci и таску
