### ISSUE TITLE
Автозагрузка тестов

### ISSUE THREAD

**Issue by leemuar** [oscript-library/asserts#5]
Для упрощения написания тестов предлагаю сделать автоматическое выполнение всех функций сценария, начинающихся с определенных ключевых слов.

Например, для файла

```
Процедура ТестПроверить_блабла() Экспорт
    // ...
КонецПроцедуры

Процедура ТестПроверить_ЕщеБлаБла() Экспорт
    // ...
КонецПроцедуры

Процедура Вспомогательная() Экспорт
    // ...
Процедура
```

Будут автоматически выполнены:
* ТестПроверить_блабла()
* ТестПроверить_ЕщеБлаБла()

Плюсы:
* упрощенный способ написания тестов

Минусы:
* невозможно составлять список нереализованных тестов

---

Предлагаю поддерживать оба режима тестирования, как с использованием метода ПолучитьСписокТестов(). так и без него (автозагрузка):

Если в файле есть метод ПолучитьСписокТестов() - получить список тестов из него.
Если в файле нет метода ПолучитьСписокТестов() - получить список методов, начинающихся с определенных ключевых слов, используя Рефлектор.

Нужно определиться со списком ключевых слов. Возможные варианты:
* Тест
* Проверить
* Test (для поддержки зарубежных товарищей в будущем)

**Comment by artbear** [comment]
Да, такая схема теперь вполне возможна, после того, как я добавил Рефлектор.
Я ее применял еще в 2004 году для тестирования 1С++ для 1С 7.7 :)

**Comment by artbear** [comment]
>невозможно составлять список нереализованных тестов

В исходном фреймворке xUnitFor1C тест может вызвать спец.метод ПропуститьТест для указания пропуска/нереализованности теста.

**Comment by artbear** [comment]
Не тот репо :( Почему не в нужном репо 1testrunner ?

**Comment by leemuar** [comment]
@artbear в 1testrunner нет возможности создать ишузы

**Comment by leemuar** [comment]
> Да, такая схема теперь вполне возможна, после того, как я добавил Рефлектор.

Да, во всех фреймворках с рефлекцией так и делают. Понятно, что библиотека портировалась с 1С и там это было сложно сделать.

**Comment by artbear** [comment]
А подпись "forked from artbear/1testrunner" под oscript-library/1testrunner ни на что не намекает? :)
