### ISSUE TITLE
Показ стэк-трейса при вызове исключения

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/asserts#7]
Основное неудобство при работе с библиотекой - отсутствие понимания, где конкретно рухнул тест. Текст исключения всегда содержит процедуру из самого asserts, с иногда понятными комментариями на сравниваемые значения. Если не указывать ДСО, то в большинстве случаев непонятно, что конкретно рухнуло. 

Движок недавно научился работать с собственным стэк-трейсом. Мы можем добавить его вывод в текст исключения для точного позиционирования и одновременно спасти пару енотов от вымирания из-за углекислого и серо-водородного газов, которые выделяются у авторов либ при написании этих либ и/или поломки тестов.

**Comment by EvilBeaver** [comment]
Евгений Ваганыч, освободите Никиту, мы знаем, что он у вас. А предложение дельное, да.

**Comment by artbear** [comment]
Напомните, какой метод нужно вызывать?
